export const setCountryFlag = (country: string): string => {
  const flags: { [key: string]: string } = {
    // Европа
    UZ: "🇺🇿 Uzbekistan",
    RU: "🇷🇺 Russia",
    UA: "🇺🇦 Ukraine",
    DE: "🇩🇪 Germany",
    FR: "🇫🇷 France",
    IT: "🇮🇹 Italy",
    ES: "🇪🇸 Spain",
    GB: "🇬🇧 United Kingdom",
    UK: "🇬🇧 United Kingdom",
    PL: "🇵🇱 Poland",
    NL: "🇳🇱 Netherlands",
    BE: "🇧🇪 Belgium",
    SE: "🇸🇪 Sweden",
    NO: "🇳🇴 Norway",
    FI: "🇫🇮 Finland",
    DK: "🇩🇰 Denmark",
    CH: "🇨🇭 Switzerland",
    AT: "🇦🇹 Austria",
    IE: "🇮🇪 Ireland",
    PT: "🇵🇹 Portugal",
    GR: "🇬🇷 Greece",
    CZ: "🇨🇿 Czech Republic",
    SK: "🇸🇰 Slovakia",
    HU: "🇭🇺 Hungary",
    RO: "🇷🇴 Romania",
    BG: "🇧🇬 Bulgaria",
    HR: "🇭🇷 Croatia",
    RS: "🇷🇸 Serbia",
    SI: "🇸🇮 Slovenia",
    LT: "🇱🇹 Lithuania",
    LV: "🇱🇻 Latvia",
    EE: "🇪🇪 Estonia",
    IS: "🇮🇸 Iceland",
    LU: "🇱🇺 Luxembourg",
    MT: "🇲🇹 Malta",
    CY: "🇨🇾 Cyprus",

    // Азия
    KZ: "🇰🇿 Kazakhstan",
    TR: "🇹🇷 Turkey",
    CN: "🇨🇳 China",
    JP: "🇯🇵 Japan",
    KR: "🇰🇷 South Korea",
    KP: "🇰🇵 North Korea",
    IN: "🇮🇳 India",
    ID: "🇮🇩 Indonesia",
    TH: "🇹🇭 Thailand",
    VN: "🇻🇳 Vietnam",
    PH: "🇵🇭 Philippines",
    MY: "🇲🇾 Malaysia",
    SG: "🇸🇬 Singapore",
    IL: "🇮🇱 Israel",
    SA: "🇸🇦 Saudi Arabia",
    AE: "🇦🇪 United Arab Emirates",
    QA: "🇶🇦 Qatar",
    KW: "🇰🇼 Kuwait",
    BH: "🇧🇭 Bahrain",
    OM: "🇴🇲 Oman",
    IR: "🇮🇷 Iran",
    IQ: "🇮🇶 Iraq",
    SY: "🇸🇾 Syria",
    LB: "🇱🇧 Lebanon",
    JO: "🇯🇴 Jordan",
    PK: "🇵🇰 Pakistan",
    BD: "🇧🇩 Bangladesh",
    LK: "🇱🇰 Sri Lanka",
    NP: "🇳🇵 Nepal",
    MM: "🇲🇲 Myanmar",
    KH: "🇰🇭 Cambodia",
    LA: "🇱🇦 Laos",
    MN: "🇲🇳 Mongolia",

    // Северная Америка
    US: "🇺🇸 United States",
    CA: "🇨🇦 Canada",
    MX: "🇲🇽 Mexico",
    CU: "🇨🇺 Cuba",
    JM: "🇯🇲 Jamaica",
    HT: "🇭🇹 Haiti",
    DO: "🇩🇴 Dominican Republic",
    PR: "🇵🇷 Puerto Rico",

    // Южная Америка
    BR: "🇧🇷 Brazil",
    AR: "🇦🇷 Argentina",
    CO: "🇨🇴 Colombia",
    PE: "🇵🇪 Peru",
    VE: "🇻🇪 Venezuela",
    CL: "🇨🇱 Chile",
    EC: "🇪🇨 Ecuador",
    BO: "🇧🇴 Bolivia",
    PY: "🇵🇾 Paraguay",
    UY: "🇺🇾 Uruguay",

    // Африка
    EG: "🇪🇬 Egypt",
    ZA: "🇿🇦 South Africa",
    NG: "🇳🇬 Nigeria",
    KE: "🇰🇪 Kenya",
    ET: "🇪🇹 Ethiopia",
    GH: "🇬🇭 Ghana",
    DZ: "🇩🇿 Algeria",
    MA: "🇲🇦 Morocco",
    TN: "🇹🇳 Tunisia",
    LY: "🇱🇾 Libya",
    SD: "🇸🇩 Sudan",
    TZ: "🇹🇿 Tanzania",
    UG: "🇺🇬 Uganda",
    AO: "🇦🇴 Angola",
    MZ: "🇲🇿 Mozambique",
    MG: "🇲🇬 Madagascar",
    CM: "🇨🇲 Cameroon",
    CI: "🇨🇮 Ivory Coast",
    SN: "🇸🇳 Senegal",

    // Океания
    AU: "🇦🇺 Australia",
    NZ: "🇳🇿 New Zealand",
    FJ: "🇫🇯 Fiji",
    PG: "🇵🇬 Papua New Guinea",
    SB: "🇸🇧 Solomon Islands",

    // Международные организации
    EU: "🇪🇺 European Union",
    UN: "🇺🇳 United Nations",
    NATO: "🇺🇳 NATO",
  };

  // Приводим код страны к верхнему регистру для поиска
  const countryCode = country.toUpperCase();

  return flags[countryCode] || `🏳️‍🌈 ${country}`;
};
